### ISSUE TITLE
Save loops to asdf

### ISSUE THREAD

**Issue by wtbarnes** [wtbarnes/synthesizAR#25]
Currently, all of the `Loop` objects in a field are saved to an HDF5 file and then reconstructed when calling `.restore()`. This takes > 1 minute for 5000 loops and reconstructing the object is a bit hacky. It would be better to save all of the loop coordinates to asdf since asdf supports serializing `SkyCoord` and `Quantity` objects.

**Comment by wtbarnes** [comment]
In order to do this, it would be best if solar coordinate frames could be serialized in asdf. I don't think this is currently possible. See sunpy/sunpy#2366

**Comment by Cadair** [comment]
also see astropy/astropy#8284

**Comment by wtbarnes** [comment]
Oh I thought `SkyCoord` serialization was already possible in asdf. Will probably hold off on this PR until that has been merged/released then.

**Comment by Cadair** [comment]
you can save the *frame* but not the actual SkyCoord. The frame is probably good enough anyway for all the solar frames.

**Comment by wtbarnes** [comment]
See https://docs.sunpy.org/en/stable/generated/gallery/saving_and_loading_data/coordinates_in_asdf.html#sphx-glr-generated-gallery-saving-and-loading-data-coordinates-in-asdf-py
