### ISSUE TITLE
"pkg_resources" package missing

### ISSUE THREAD

**Issue by adolliou** [wtbarnes/synthesizAR#92]
Hello,
First of all, thank you very much for this code.  

I wanted to try to run the example simulating the AIA 171 from a bundle of strands (loop-bundle-rtv.py), and ran into the following error:

```bash
Traceback (most recent call last):
  File "C:\Users\adolliou\PycharmProjects\analyze_HYDRAD_output\synthetize_AR.py", line 17, in <module>
    from synthesizAR.instruments import InstrumentSDOAIA
  File "C:\Users\adolliou\PycharmProjects\analyze_HYDRAD_output\.venv\Lib\site-packages\synthesizAR\instruments\__init__.py", line 6, in <module>
    from .sdo import *
  File "C:\Users\adolliou\PycharmProjects\analyze_HYDRAD_output\.venv\Lib\site-packages\synthesizAR\instruments\sdo.py", line 6, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

```

is pkg_resources a private repo ? 

Bests, 

Antoine

**Comment by wtbarnes** [comment]
That's surprising. How are you installing `synthesizAR`?

**Comment by adolliou** [comment]
Hi, 

I dida pip install git+https://github.com/wtbarnes/synthesizAR in my virtual environment. 

Bests, 
Antoine

**Comment by adolliou** [comment]
Hi,
 
Everything works fine by using the xrtpy from pypi. 

Thank you for your help. 

Antoine

**Comment by wtbarnes** [comment]
Great! Would you mind creating an issue on the xrtpy repository as well? They might not be aware that this is broken.

**Comment by adolliou** [comment]
Hi, sure. Here it is https://github.com/HinodeXRT/xrtpy/issues/239

Bests, 

Antoine

**Comment by joyvelasquez** [comment]
Thank you, @wtbarnes , for addressing @adolliou. @adolliou, thank you for using XRTpy and bringing this to our attention. I will review the issue.

**Comment by wtbarnes** [comment]
I'm going to close this as it is an upstream issue. Feel free to reopen as needed.
